quotes/quotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('quotesapp.urls')),
                  path('users/', include('users.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views
from .forms import LoginForm
from .views import RegisterView

app_name = 'users'

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(redirect_authenticated_user=True, template_name='login.html',
                                     authentication_form=LoginForm), name="login"),
    path("logout/", LogoutView.as_view(template_name='logout.html'), name="logout"),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default_avatar.png', upload_to='profile_images')

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

quotes/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Петро"})
    )

    last_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Петренко"})
    )

    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "username"})
    )

    email = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Email"})
    )

    password1 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Пароль"})
    )

    password2 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Повторіть пароль"})
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Username"})
    )

    password = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Password"})
    )

    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ['avatar']

quotes/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from .forms import RegisterForm, LoginForm, ProfileForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required


class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="quote:index")

        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {"form": self.form_class()})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if not form.is_valid():
            form.save()
            messages.success(request, f'Ваш акаунт успішно створено: {form.cleaned_data["username"]}')
            return redirect(to="users:login")
        return render(request, self.template_name, {"form": self.form_class()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect('users:logout')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes_site:index')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='noteapp:main')


@login_required
def profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users:profile')

    profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'users/profile.html', {'profile_form': profile_form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

quotes/users/templates/login.html
{% extends "quotesapp/base.html" %}

{% block content %}

{% if messages %}
<div xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    <span>{{ form.non_field_errors }}</span>
</div>
{% endif %}

<div class="container">
    <form class="login-form" action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Username:</label>
            {{ form.username }}
            <span class="form-error">{{ form.errors.first_name }}</span>
        </div>
        <div class="form-group">
            <label for="id_password">Password:</label>
            {{ form.password }}
            <span class="form-error">{{ form.errors.password }}</span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
        <div class="small text-center">
            <a href="{% url " users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
        </div>
    </form>
</div>


{% endblock %}

quotes/users/templates/logout.html
{% extends "quotesapp/base.html" %}

{% block content %}

<div class="container">
    <h1>Good buy!</h1>
</div>

{% endblock %}

quotes/users/templates/password_reset.html
{% extends "quotes_site/base.html" %}

{% block body %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock body %}

quotes/users/templates/password_reset_complete.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

quotes/users/templates/password_reset_confirm.html
{% extends "quotes_site/base.html" %}

{% block body %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

quotes/users/templates/profile.html
{% extends "quotesapp/base.html" %}

{% block content %}

<div>
    <h1>Profile page: {{user.username}}</h1>
    <img src="{{ user.profile.avatar.url }}" alt="avatar of user"/>
</div>

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col-md-5">
            <div class="form-group">
                <label class="small mb-1">Change Avatar:</label>
                {{ profile_form.avatar }}
                <span>{{ profile_form.errors.avatar }}</span>
            </div>
        </div>
    </div>
    <div class="grid">
        <button type="submit">Save Changes</button>
        <button type="reset" class="secondary">Reset</button>
    </div>

</form>

{% endblock content %}

quotes/users/templates/register.html
{% extends "quotesapp/base.html" %}

{% block content %}
<div class="container">
    <form class="login-form" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.first_name.id_for_label }}">First Name</label>
            {{ form.first_name }}
            <span>{{form.errors.first_name}}</span>
        </div>
        <div class="form-group">
            <label for="{{ form.last_name.id_for_label }}">Last Name</label>
            {{ form.last_name }}
            <span>{{form.errors.last_name}}</span>
        </div>
        <div class="form-group">
            <label for="{{ form.username.id_for_label }}">Username</label>
            {{ form.username }}
            <span>{{form.errors.username}}</span>
        </div>
        <div class="form-group">
            <label for="{{ form.email.id_for_label }}">Email</label>
            {{ form.email }}
            <span>{{form.errors.email}}</span>
        </div>
        <div class="form-group">
            <label for="{{ form.password1.id_for_label }}">Password</label>
            {{ form.password1 }}
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="form-group">
            <label for="{{ form.password2.id_for_label }}">Confirm password</label>
            {{ form.password2 }}
            <span>{{form.errors.password2}}</span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Sign Up</button>
        </div>
    </form>
</div>

{% endblock %}