quotes/quotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('quotesapp.urls')),
                  path('users/', include('users.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/quotesapp/urls.py
from django.urls import path
from . import views

app_name = 'quotesapp'

urlpatterns = [
    path('', views.QuoteView.as_view(), name='index'),
    path('quotes/add/', views.QuoteView.as_view(), name='add-quote'),
    path('quotes/scrape/', views.QuoteView.as_view(), name='scrape-quotes'),
    path('quotes/edit/<int:pk>', views.QuoteUpdateView.as_view(), name='edit'),
    path('quotes/remove/<int:pk>', views.QuoteRemoveView.as_view(), name='remove'),
    path('tag/<str:tag>', views.QuoteView.as_view(), name='search-tag'),
    path('tag/add/', views.TagView.as_view(), name='add-tags'),
    path('author/<str:author>', views.AuthorView.as_view(), name='author'),
    path('author/add/', views.AuthorView.as_view(), name='add-author'),
    path('author/edit/<int:pk>', views.AuthorUpdateView.as_view(), name='edit-author'),
    path('example_fill_db', views.example_fill_db, name='example-fill-db'),
]

quotes/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views
from .forms import LoginForm
from .views import RegisterView

app_name = 'users'

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(redirect_authenticated_user=True, template_name='login.html',
                                     authentication_form=LoginForm), name="login"),
    path("logout/", LogoutView.as_view(template_name='logout.html'), name="logout"),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/quotesapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=255, blank=False)
    birthday = models.DateTimeField(max_length=25, blank=False)
    born = models.CharField(max_length=25, blank=False)
    description = models.CharField(max_length=150, blank=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'fullname'], name='author of username')
        ]

    def __str__(self):
        return f"{self.fullname}"


class Tag(models.Model):
    tag = models.CharField(max_length=25, null=False, blank=False)

    def __str__(self):
        return f"{self.tag}"


class Quote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
    quote = models.TextField(null=False, blank=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='quotes', blank=False)
    tags = models.ManyToManyField(Tag, blank=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'quote'], name='quote of username')
        ]

    def __str__(self):
        return f"{self.quote}"

quotes/quotesapp/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField, ModelMultipleChoiceField
from .models import Quote, Author, Tag, User


class TagForm(ModelForm):
    tag = CharField(max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['tag']


class QuoteForm(ModelForm):
    author = ModelChoiceField(queryset=Author.objects.none())
    tags = ModelMultipleChoiceField(queryset=Tag.objects.none())

    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']

    def __init__(self, user: User, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].queryset = Author.objects.filter(user=user)
        self.fields['tags'].queryset = Tag.objects.all()


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'birthday', 'born', 'description']

quotes/quotesapp/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.db.models import Count
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView, DeleteView, View

from .forms import QuoteForm, TagForm, AuthorForm
from .models import Tag, Author, Quote
# from quotes.service.scrape_quotes import scrape_quotes


class AuthorUpdateView(UpdateView):
    model = Author
    fields = ['fullname', 'birthday', 'born', 'description']
    template_name = 'quotesapp/edit_author.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        return obj if obj.user == self.request.user else Http404()

    def get_success_url(self):
        return reverse_lazy('quote:author', kwargs={'author': self.object.fullname})


class QuoteUpdateView(UpdateView):
    model = Quote
    fields = ['quote', 'author', 'tags']
    success_url = reverse_lazy('quote:index')
    template_name = 'quotesapp/edit_quote.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        return obj if obj.user == self.request.user else Http404()

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url

        return self.success_url


class QuoteRemoveView(DeleteView):
    model = Quote
    success_url = reverse_lazy('quotesapp:index')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        return obj if obj.user == self.request.user else Http404()

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url

        return redirect('quotesapp:index')


class QuoteView(View):
    quotes_per_page = 10
    template_get = 'quotesapp/quotes.html'
    template_add = 'quotesapp/add_quote.html'
    form_class = QuoteForm
    model = Quote

    def dispatch(self, request, *args, **kwargs):
        if request.method == 'GET':
            if 'add' in request.path:
                return self.get_form(request)
            # elif 'scrape' in request.path:
            #     return self.scrape(request)

        return super().dispatch(request, *args, **kwargs)

    def get(self, request, **kwargs):
        match kwargs:
            case {'tag': tag}:
                quotes = self.model.objects.filter(tags__name=tag).order_by('-id')  # noqa
            case _:
                quotes = self.model.objects.all().order_by('-id')  # noqa

        top_tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]  # noqa

        paginator = Paginator(quotes, self.quotes_per_page)

        context = {
            'page_obj': paginator.get_page(request.GET.get('page')),
            'user': request.user,
            'top_tags': top_tags,
            'by_tag': kwargs.get('tag'),
        }
        return render(request, self.template_get, context)

    # @method_decorator(login_required)
    # def scrape(self, request):
    #     scrape_quotes(request.user)
    #     return redirect('quote:index')

    @method_decorator(login_required)
    def get_form(self, request):
        return render(request, self.template_add, {'form': self.form_class(request.user)})

    @method_decorator(login_required)
    def post(self, request):
        form = self.form_class(request.user, request.POST)

        if not form.is_valid():
            return render(request, self.template_add, {'form': form})

        try:
            new_quote = form.save(commit=False)
            new_quote.user = request.user

            new_quote.save()
            form.save_m2m()

        except IntegrityError as e:
            if 'unique constraint "quote of username"' in str(e):
                form.add_error('quote', "This quote already exists. Please add a new quote.")

            return render(request, self.template_add, {'form': form})

        return redirect('quotesapp:index')


class AuthorView(View):
    template_get = 'quotesapp/author.html'
    template_add = 'quotesapp/add_author.html'
    form_class = AuthorForm
    model = Author

    def dispatch(self, request, *args, **kwargs):
        if request.method == 'GET' and 'add' in request.path:
            return self.get_form(request)

        return super().dispatch(request, *args, **kwargs)

    def get(self, request, author: str):
        context = {
            "author": self.model.objects.get(fullname=author),  # noqa
            "user": request.user,
        }
        return render(request, self.template_get, context)

    @method_decorator(login_required)
    def get_form(self, request):
        return render(request, self.template_add, {'form': self.form_class()})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if not form.is_valid():
            return render(request, self.template_add, {'form': form})

        try:
            new_author = form.save(commit=False)
            new_author.user = request.user
            new_author.save()
        except IntegrityError as e:
            if 'unique constraint "author of username"' in str(e):
                form.add_error("fullname", "Error!!!")

            return render(request, self.template_add, {'form': form})

        return redirect(to='quotesapp:index')


class TagView(View):
    template_name = 'quotesapp/add_tags.html'
    form_class = TagForm
    model = Tag

    @method_decorator(login_required)
    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class()})

    @method_decorator(login_required)
    def post(self, request):
        form = self.form_class(request.POST)

        if not form.is_valid():
            return render(request, self.template_name, {'form': form})

        tag = form.save(commit=False)
        tag.user = request.user
        tag.save()
        return redirect(to='quotesapp:index')


@login_required
def example_fill_db(request):
    author, _ = Author.objects.get_or_create(
        user=request.user,
        fullname='fullname',
        defaults={
            'birthday': 'birthday',
            'born': 'born',
            'description': 'description',
        }
    )
    tag, _ = Tag.objects.get_or_create(name='Test name')
    quote, _ = Quote.objects.get_or_create(
        user=request.user,
        quote='lorem ipsum',
        defaults={
            'author': author
        }
    )
    quote.tags.add(tag)
    return redirect(to='quotesapp:index')

quotes/quotesapp/templates/quotesapp/add_author.html
{% extends "quotesapp/base.html" %}

{% block content %}

<div class="container">
    <form method="POST" action="{% url 'quotesapp:add-author' %}">
        {% csrf_token %}
        <div class="form-group">
            <label> Author fullname:
                {{ form.fullname }}
            </label>
            <span>{{ form.errors.fullname }}</span>
        </div>
        <div class="form-group">
            <label>Birthday:
                {{ form.birthday }}
            </label>
            <span>{{ form.errors.Birthday }}</span>
        </div>
        <div class="form-group">
            <label> Born:
                {{ form.born }}
            </label>
            <span>{{ form.errors.born }}</span>
        </div>
        <label> Description:</label>
        <div class="form-group">
            {{ form.description }}
            <span>{{ form.errors.description }}</span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>
</div>
{% endblock %}

quotes/quotesapp/templates/quotesapp/add_quote.html
{% extends "quotesapp/base.html" %}

{% block content %}

<div class="container">
    <form method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
<!--    <a href="{% url 'quote:scrape-quotes' %}" class="btn btn-link float-right">Scrape from http://quotes.toscrape.com</a>&ndash;&gt;-->
    </form>
</div>
{% endblock %}

quotes/quotesapp/templates/quotesapp/add_tags.html
{% extends "quotesapp/base.html" %}

{% block content %}

<div class="container">
    <form method="POST" action="{% url 'quotesapp:add-tags' %}">
        {% csrf_token %}
        <div class="form-group">
            <label>Enter the tag name:
                {{form.tag}}
            </label>
            <span>{{ form.errors.tag }}</span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>
</div>

{% endblock %}

quotes/quotesapp/templates/quotesapp/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}My quotes!{% endblock %}</title>
  {% bootstrap_css %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'quotesapp/main.css' %}">
</head>
<body>
  <header>
    <h1>Quotes</h1>
    <nav>
      <ul class="nav-left">
        <li><a href="/">Quotes</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'quotesapp:add-quote' %}">Add quote</a></li>
          <li><a href="{% url 'quotesapp:add-author' %}">Add author</a></li>
          <li><a href="{% url 'quotesapp:add-tags' %}">Add tags</a></li>
<!--          <li><a href="{% url 'quotesapp:example-fill-db' %}">Non Form Example</a></li>-->
        {% endif %}
      </ul>
      <ul class="nav-right">
        {% if user.is_authenticated %}
          <li><a href="{% url 'users:logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'users:register' %}">Create account</a></li>
          <li><a href="{% url 'users:login' %}">Login</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
    {% block content %}
    {% endblock %}
</body>
</html>

quotes/quotesapp/templates/quotesapp/quotes.html
{% extends 'quotesapp/base.html' %}

{% block title %}
Quotes
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1 class="my-4">Quotes</h1>
            {% if by_tag %}
            <h3>Viewing tag: <a href="{% url 'quote:search-tag' by_tag %}">{{ by_tag }}</a></h3>
            {% endif %}
            <ul class="list-group quote-list">
                {% for quote in page_obj %}
                <li class="list-group-item quote-item">
                    <div class="quote-text"><i>“{{ quote.quote }}”</i></div>
                    <div class="quote-author">by
                        <a href="{% url 'quote:author' quote.author %}"><b>{{ quote.author }}</b></a>
                    </div>
                    <div class="quote-tags">
                        <small>Tags:</small>
                        {% for tag in quote.tags.all %}
                        <span class="badge badge-pill badge-sm badge-warning">
                        <a href="{% url 'quote:search-tag' tag.name %}"><i>{{ tag.tag }}</i></a>
                      </span>
                        {% empty %}
                        <span class="badge badge-pill badge-sm badge-warning">
                        ---
                      </span>
                        {% endfor %}
                    </div>
                    {% if user == quote.user %}
                    <div class="quote-actions mt-3">
                        <a href="{% url 'quote:edit' quote.id %}?next={{ request.path }}{% if page_obj.has_previous or page_obj.has_next %}?page={{ page_obj.number }}{% endif %}"
                           class="btn btn-warning mr-2">Edit</a>
                        <a href="{% url 'quote:remove' quote.id %}?next={{ request.path }}{% if page_obj.has_previous or page_obj.has_next %}?page={{ page_obj.number }}{% endif %}"
                           class="btn btn-danger">Delete</a>
                    </div>
                    {% endif %}
                </li>
                {% empty %}
                <li class="list-group-item">No quotes found.</li>
                {% endfor %}
            </ul>

            {% if page_obj.has_previous or page_obj.has_next %}
            <nav>
                <ul class="nav-left">
                    {% if page_obj.has_previous %}
                    <li class="previous">
                        <a href="?page={{ page_obj.previous_page_number }}"><span aria-hidden="true">←</span>
                            Previous</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="nav-right">
                    {% if page_obj.has_next %}
                    <li class="next ml-auto">
                        <a href="?page={{ page_obj.next_page_number }}">Next <span aria-hidden="true">→</span></a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
        <div class="col-md-4">
            <h2>Top Ten tags</h2>
            <ol>
                {% for tag in top_tags %}
                <li>
                    <a href="{% url 'quote:search-tag' tag.tag %}">{{ tag.tag }}</a>
                </li>
                {% endfor %}
            </ol>
        </div>
    </div>
</div>
{% endblock %}